preprocessing:
  input_path:  data/raw/constraint_category.csv 
  output_path: data/processed/instruction_dataset_with_characteristics_list.csv
  prompt_path: prompts/constraint_prompts.yaml
  column_name: Characteristics
  model_name: gpt-4o-mini


constraint_category_generation:
  input_path: data/processed/instruction_dataset_with_characteristics_list.csv
  output_path: data/processed/constraint_categories.yaml
  model: gpt-4o-mini
  prompt_path: scripts/constraints/prompts/constraint_prompts.yaml
  prompt_log_path: data/outputs/constraint_category_prompt_log.txt

