datasets:
  - name: MaziyarPanahi/Synthia-Coder-v1.5-I-sharegpt
    split: train
  - name: xlangai/DS-1000
    split: test
  - name: bigcode/bigcodebench
    split: v0.1.4
  - name: Multilingual-Multimodal-NLP/McEval-Instruct
    split: train
  - name: nuprl/CanItEdit
    split: test