constraint_prompts: scripts/constraints/prompts/constraint_prompts.yaml
datasets: config/datasets.yaml
constraint_tasks: config/constraint_tasks.yaml
constraint_categories: data/processed/constraint_categories.yaml